name: CI

on:
  push:
    branches:
      -master
  schedule:
    - cron: 0 */6 * * *

jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: fujunchao/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          upstream_repository: LmeSzinc/AzurLaneAutoScript
          target_repository: fujunchao/AzurLaneAutoScript
          upstream_branch: master
          target_branch: master
          force: false
          tags: true
